//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activiter
    {
        public int id_activiter { get; set; }
        public Nullable<int> id_job { get; set; }
        public Nullable<int> id_personne { get; set; }
        public string email_postuler { get; set; }
        public string datePostulation { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
