//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condidat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Condidat()
        {
            this.Postuler = new HashSet<Postuler>();
        }
    
        public int id_personne { get; set; }
        public Nullable<int> id_user { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string username { get; set; }
        public string cv { get; set; }
        public string gouvernorat { get; set; }
        public Nullable<int> tel { get; set; }
        public string sexe { get; set; }
        public Nullable<int> id_competence { get; set; }
        public string competence { get; set; }
        public string datenaissance { get; set; }
    
        public virtual Competence Competence1 { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postuler> Postuler { get; set; }
    }
}
