//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public int id_entreprise { get; set; }
        public Nullable<int> id_user { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string nom_entreprise { get; set; }
        public string gouvernorat { get; set; }
        public Nullable<int> tel { get; set; }
        public string sexe { get; set; }
        public Nullable<int> id_activité { get; set; }
        public string activite { get; set; }
        public string datenaissance { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
