//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinale
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FREELANCEEntities1 : DbContext
    {
        public FREELANCEEntities1()
            : base("name=FREELANCEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activiter> Activiter { get; set; }
        public virtual DbSet<Competence> Competence { get; set; }
        public virtual DbSet<Compte> Compte { get; set; }
        public virtual DbSet<Condidat> Condidat { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Postuler> Postuler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
