//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postuler
    {
        public int id_post { get; set; }
        public Nullable<int> id_personne { get; set; }
        public string description { get; set; }
        public string datePostulation { get; set; }
        public string budgee { get; set; }
        public string duree { get; set; }
    
        public virtual Condidat Condidat { get; set; }
    }
}
